### ISSUE TITLE
In Flatpak builds, flashing firmware from file using the file chooser does not work.

### ISSUE THREAD

**Issue by thomas-profitt** [theironrobin/siglo#52] opened 2021-05-29 21:46 UTC
Tested with 1af26db, on a PinePhone running postmarketOS,
when the file chooser button is tapped or clicked,
nothing happens within Siglo's UI,
and the Flatpak file chooser portal error in the screenshot below is seen.
![siglo-flatpak-file-chooser-bug](https://user-images.githubusercontent.com/13843293/120085364-c489f380-c094-11eb-92b6-85af41bf887c.png)

**Comment by alexr4535** [comment] 2021-06-01 14:47
I keep forgetting you have to manually bump the flatpak version each time you re-tag. Try it now and report if it works or not, please.

**Comment by thomas-profitt** [comment] 2021-06-04 01:44
I rebuilt my siglo.flatpak, from b54a4e7, installed it, and still had the problem.

**Comment by nlfx** [comment] 2021-06-28 16:21
@thomas-profitt I'm using the flatpak on postmarketOS v21.03.1 and it works fine for me.

Given the error message, maybe you are missing the `xdg-desktop-portal-gtk` or `xdg-desktop-portal` package? On pmOS v21.03.1 it's a dependency of `postmarketos-ui-phosh` so it should be installed by default. I have not tested on pmOS Edge.

If you are using pmOS Edge, and both packages are installed, it might be a bug in how phosh interacts with D-Bus, when phosh is started with `dbus-run-session /usr/bin/phosh`?

Note: with `xdg-desktop-portal` you should not need to run the flatpak with host filesystem access.

**Comment by theironrobin** [comment] 2022-06-21 22:43
closing since question was never answered and it seems like this problem is not reproduced

**Closed by theironrobin** 2022-06-21 22:43 UTC
Labels: question
